/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.upnorte.talbd.nuevonorte.presentacion;

import edu.upnorte.talbd.nuevonorte.accesodatos.DAODocumento;
import edu.upnorte.talbd.nuevonorte.entidades.Documento;
import java.util.List;
import javax.swing.JDesktopPane;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author MARGARITA
 */
public class ListarDocumento extends javax.swing.JInternalFrame {

    List<Documento> listaDocumento;
    JDesktopPane dskPrincipal;
    public ListarDocumento(JDesktopPane dskPrincipal) {
        initComponents();
        //actualizarTabla();
        this.dskPrincipal = dskPrincipal;
        mostrar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblDocumento = new javax.swing.JTable();
        btnModificar = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Lista de Documentos");

        tblDocumento.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tblDocumento);

        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 444, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(btnModificar)))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(92, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnModificar)
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        int index = tblDocumento.getSelectedRow();
        if (index != -1){
            //Modificamos la fila seleccionada
            Documento objDocumento = listaDocumento.get(index);
            ModificarDocumento ventana = new ModificarDocumento(objDocumento,this);
            dskPrincipal.add(ventana);
            ventana.setVisible(true);
            mostrar();
        }else{
            JOptionPane.showMessageDialog(this,"Se necesita seleccionar una fila!");
        }
    }//GEN-LAST:event_btnModificarActionPerformed

    public void mostrar(){
        //1. Traemos objetos
        listaDocumento = DAODocumento.getInstance().listar();
        //2. Creamos modelo
        DefaultTableModel modelo = new DefaultTableModel();
        //3. Agregamos columnas al modelo
        modelo.addColumn("ID");
        modelo.addColumn("Nombre");
        //4. Agregamos filas al modelo
        for (Documento c : listaDocumento){
            modelo.addRow(new Object[]{
                c.getId(),
                c.getNombre()
            });
        }
        //5. Asignamos el modelo a la tabla
        tblDocumento.setModel(modelo);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnModificar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblDocumento;
    // End of variables declaration//GEN-END:variables
}