/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.upnorte.talbd.nuevonorte.presentacion;

import edu.upnorte.talbd.nuevonorte.accesodatos.DAOPagina;
import edu.upnorte.talbd.nuevonorte.entidades.Pagina;
import java.util.List;
import javax.swing.JDesktopPane;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author MARGARITA
 */
public class ListarPagina extends javax.swing.JInternalFrame {

    
    List<Pagina> listaPagina;
    JDesktopPane dskPrincipal;
    
    public ListarPagina(JDesktopPane dskPrincipal) {
        initComponents();
        this.dskPrincipal = dskPrincipal;
        mostrar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblPagina = new javax.swing.JTable();
        btnModificar = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Lista de Paginas");

        tblPagina.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tblPagina);

        btnModificar.setText("ModificarPagina");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnModificar)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 579, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnModificar)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        int index = tblPagina.getSelectedRow();
        if (index != -1){
            //Modificamos la fila seleccionada
            Pagina objPagina = listaPagina.get(index);
            ModificarPagina ventana = new ModificarPagina(objPagina,this);
            dskPrincipal.add(ventana);
            ventana.setVisible(true);
            mostrar();
        }else{
            JOptionPane.showMessageDialog(this,"Se necesita seleccionar una fila!");
        }
    }//GEN-LAST:event_btnModificarActionPerformed

    
    public void mostrar(){
        //1. Traemos objetos
        listaPagina = DAOPagina.getInstance().listar();
        //2. Creamos modelo
        DefaultTableModel modelo = new DefaultTableModel();
        //3. Agregamos columnas al modelo
        modelo.addColumn("ID");
        modelo.addColumn("Nombre");
        modelo.addColumn("Precio");
        //4. Agregamos filas al modelo
        for (Pagina c : listaPagina){
            modelo.addRow(new Object[]{
                c.getId(),
                c.getNombre(),
                c.getPrecio()
            });
        }
        //5. Asignamos el modelo a la tabla
        tblPagina.setModel(modelo);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnModificar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblPagina;
    // End of variables declaration//GEN-END:variables
}