/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.upnorte.talbd.nuevonorte.presentacion;

import edu.upnorte.talbd.nuevonorte.accesodatos.DAOMedida;
import edu.upnorte.talbd.nuevonorte.entidades.Medida;
import java.util.List;
import javax.swing.JDesktopPane;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author MARGARITA
 */
public class ListarMedida extends javax.swing.JInternalFrame {

    List<Medida> listaMedida;
    JDesktopPane dskPrincipal;
    
    public ListarMedida(JDesktopPane dskPrincipal) {
        initComponents();
        //actualizarTabla();
        this.dskPrincipal = dskPrincipal;
        mostrar();
    }
    
    
   /* public ListarMedida() {
        initComponents();
    }*/

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblMedida = new javax.swing.JTable();
        btnModificar = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Lista de Medidas");

        tblMedida.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tblMedida);

        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnModificar)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 552, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(61, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(btnModificar)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed

        int index = tblMedida.getSelectedRow();
        if (index != -1){
            //Modificamos la fila seleccionada
            Medida objMedida = listaMedida.get(index);
            ModificarMedida ventana = new ModificarMedida(objMedida,this);
            dskPrincipal.add(ventana);
            ventana.setVisible(true);
            mostrar();
        }else{
            JOptionPane.showMessageDialog(this,"Se necesita seleccionar una fila!");
        }
        
    }//GEN-LAST:event_btnModificarActionPerformed

    
    public void mostrar(){
        //1. Traemos objetos
        listaMedida = DAOMedida.getInstance().listar();
        //2. Creamos modelo
        DefaultTableModel modelo = new DefaultTableModel();
        //3. Agregamos columnas al modelo
        modelo.addColumn("ID");
        modelo.addColumn("Nombre");
        modelo.addColumn("Ancho");
        modelo.addColumn("Alto");
        modelo.addColumn("P. Venta");
        modelo.addColumn("P. Costo");
        //4. Agregamos filas al modelo
        for (Medida c : listaMedida){
            modelo.addRow(new Object[]{
                c.getId(),
                c.getNombre(),
                c.getAncho(),
                c.getAlto(),
                c.getPreciocosto(),
                c.getPrecioventa()
            });
        }
        //5. Asignamos el modelo a la tabla
        tblMedida.setModel(modelo);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnModificar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblMedida;
    // End of variables declaration//GEN-END:variables
}