/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.upnorte.talbd.nuevonorte.presentacion;

import edu.upnorte.talbd.nuevonorte.accesodatos.DAOAviso;
import edu.upnorte.talbd.nuevonorte.accesodatos.DAOCategoria;
import edu.upnorte.talbd.nuevonorte.accesodatos.DAOColor;
import edu.upnorte.talbd.nuevonorte.accesodatos.DAOMedida;
import edu.upnorte.talbd.nuevonorte.accesodatos.DAOPagina;
import edu.upnorte.talbd.nuevonorte.entidades.Aviso;
import edu.upnorte.talbd.nuevonorte.entidades.Categoria;
import edu.upnorte.talbd.nuevonorte.entidades.Color;
import edu.upnorte.talbd.nuevonorte.entidades.Medida;
import edu.upnorte.talbd.nuevonorte.entidades.Pagina;
import java.math.BigDecimal;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author MARGARITA
 */
public class ModificarAviso extends javax.swing.JInternalFrame {

    
    private Aviso objAviso;
    private ListarAviso lista;
    
    public ModificarAviso(Aviso objAviso,ListarAviso lista) {
        initComponents();
        this.objAviso = objAviso;
        txtId.setText("" + objAviso.getId());
        txtPrecio.setText(objAviso.getPrecio().toString());
        txtFecha.setDate(objAviso.getFecha());
        
        //ComboBox Medida
        List<Medida> lstMedida = DAOMedida.getInstance().listar();
        String[] lstMedidaC =  new String[lstMedida.size()];
        int i =0,j =0;
        for (Medida item : lstMedida) {
            lstMedidaC[i++] = item.getNombre();
            if(objAviso.getIdMedida().getId()==item.getId())
                j = i-1;
        }
        cmbMedida.setModel(new javax.swing.DefaultComboBoxModel(lstMedidaC));
        cmbMedida.setSelectedIndex(j);
        
        
        //ComboBox Color
        List<Color> lstColor = DAOColor.getInstance().listar();
        String[] lstColorC =  new String[lstColor.size()];
        int a =0,b =0;
        for (Color item : lstColor) {
            lstColorC[a++] = item.getNombre();
            if(objAviso.getIdColor().getId()==item.getId())
                b = a-1;
        }
        cmbColor.setModel(new javax.swing.DefaultComboBoxModel(lstColorC));
        cmbColor.setSelectedIndex(b);
        
        
        //ComboBox Pagina
        List<Pagina> lstPagina = DAOPagina.getInstance().listar();
        String[] lstPaginaC =  new String[lstPagina.size()];
        int c =0,d =0;
        for (Pagina item : lstPagina) {
            lstPaginaC[c++] = item.getNombre();
            if(objAviso.getIdPagina().getId()==item.getId())
                d = c-1;
        }
        cmbPagina.setModel(new javax.swing.DefaultComboBoxModel(lstPaginaC));
        cmbPagina.setSelectedIndex(d);
        
        
        //ComboBox Categoria
        List<Categoria> lstCategoria = DAOCategoria.getInstance().listar();
        String[] lstCategoriaC =  new String[lstCategoria.size()];
        int e =0,f =0;
        for (Categoria item : lstCategoria) {
            lstCategoriaC[e++] = item.getNombre();
            if(objAviso.getIdCategoria().getId()==item.getId())
                f = e-1;
        }
        cmbCategoria.setModel(new javax.swing.DefaultComboBoxModel(lstCategoriaC));
        cmbCategoria.setSelectedIndex(f);
        
        
        this.lista = lista;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        txtPrecio = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtFecha = new com.toedter.calendar.JDateChooser();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btnGuardar = new javax.swing.JButton();
        cmbMedida = new javax.swing.JComboBox();
        cmbColor = new javax.swing.JComboBox();
        cmbPagina = new javax.swing.JComboBox();
        cmbCategoria = new javax.swing.JComboBox();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Modificar Aviso");

        jLabel1.setText("ID:");

        jLabel2.setText("Precio:");

        txtId.setEditable(false);

        jLabel3.setText("Fecha:");

        jLabel4.setText("Medida:");

        jLabel5.setText("Color:");

        jLabel6.setText("Pagina:");

        jLabel7.setText("Categoria:");

        btnGuardar.setText("Guadar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        cmbMedida.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cmbColor.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cmbPagina.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cmbCategoria.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtId, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                                    .addComponent(txtPrecio)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel7)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(cmbCategoria, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel6)
                                    .addGap(18, 18, 18)
                                    .addComponent(cmbPagina, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel4)
                                        .addComponent(jLabel5))
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(cmbMedida, 0, 112, Short.MAX_VALUE)
                                        .addComponent(cmbColor, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addComponent(btnGuardar)))
                .addContainerGap(62, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cmbMedida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cmbColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cmbPagina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(cmbCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addComponent(btnGuardar)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        try{
        objAviso.setPrecio(BigDecimal.valueOf(Double.valueOf(txtPrecio.getText())));
        objAviso.setFecha(txtFecha.getDate());
        
        List<Medida> lstMedida = DAOMedida.getInstance().listar();
        objAviso.setIdMedida(lstMedida.get(cmbMedida.getSelectedIndex()));
        
        List<Color> lstColor = DAOColor.getInstance().listar();
        objAviso.setIdColor(lstColor.get(cmbColor.getSelectedIndex()));
        
        List<Pagina> lstPagina = DAOPagina.getInstance().listar();
        objAviso.setIdPagina(lstPagina.get(cmbPagina.getSelectedIndex()));
        
        List<Categoria> lstCategoria = DAOCategoria.getInstance().listar();
        objAviso.setIdCategoria(lstCategoria.get(cmbCategoria.getSelectedIndex()));
        
        //modificamos la bd
        boolean r = DAOAviso.getInstance().modificar(objAviso);
        if (r == true){
            JOptionPane.showMessageDialog(this, "Pagina modificada con exito!");
            this.dispose();
        }else{
            JOptionPane.showMessageDialog(this, "No se pudo modificar la pagina");
        }
        lista.mostrar();
        }catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardar;
    private javax.swing.JComboBox cmbCategoria;
    private javax.swing.JComboBox cmbColor;
    private javax.swing.JComboBox cmbMedida;
    private javax.swing.JComboBox cmbPagina;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private com.toedter.calendar.JDateChooser txtFecha;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtPrecio;
    // End of variables declaration//GEN-END:variables
}
